### ISSUE TITLE
`new MongoClient();` throws error in serverless setting

### ISSUE THREAD

**Issue by bfaulk96** [manyuanrong/deno_mongo#117]
I have a serverless function deployed to Vercel (using vercel-deno), and while this library appears to work locally, I get the following error when trying to call `new MongoClient();` in the serverless context:
```bash
error: Uncaught Error: Read-only file system (os error 30)
    at processResponse (core.js:226:13)
    at Object.jsonOpAsync (core.js:244:12)
    at async Object.mkdir (deno:cli/rt/30_fs.js:100:5)
    at async download (mod.ts:34:3)
    at async prepare (mod.ts:61:21)
    at async init (util.ts:44:3)
    at async mod.ts:14:1
RequestId: c8dba0ab-e6f2-48ff-8da7-d5bc21926900 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```
Any ideas what might be causing this? The function is deployed with the `--allow-all` flag.
I think the issue occurs in [deno-plugin-prepare](https://github.com/manyuanrong/deno-plugin-prepare) (more specifically, [this line](https://github.com/manyuanrong/deno-plugin-prepare/blob/master/mod.ts#L34)), which is used by this repo.

**Comment by lowray** [comment]
This problem caused by the plugin.
serverless (eg. vercel) do not allow you to write into filesystem.
I had the same problem [here](https://github.com/TooTallNate/vercel-deno/issues/40).
i hope we can find a solution so we can use the package without plugins.

**Comment by manyuanrong** [comment]
Please try to set DENO_PLUGIN_DIR environment variable in /tmp to solve this problem

**Comment by bfaulk96** [comment]
@manyuanrong Thanks for the suggestion, I will try that. As @lowray said, this seems to be an issue specific to using the Deno plugins with serverless functions in Vercel, so I will close this issue, as it's not an issue specific to this library.
