### ISSUE TITLE
only return specific fields in document returned from .find()

### ISSUE THREAD

**Issue by Schoude** [manyuanrong/deno_mongo#121]
[Feature in the MongoDB Docs "Project Fields to Return from Query"](https://docs.mongodb.com/manual/tutorial/project-fields-from-query-results/)

This lets the developer chose the **return only specific fields** from the documents that should be found.

Imagine a doc like this
``` {
_id: {$oid: "f58d5989-83aa-481c-93b4-f5fdacf9fc9b"},
item: "planner", 
qty: 75, 
tags: ["blank", "red"],
dim_cm: [ 22.85, 30 ] },
```

Use cases:

1. don't return the specified fields but all the rest
`db.collection.find({}, {item: 0 })`
would return
``` {
_id: {$oid: "f58d5989-83aa-481c-93b4-f5fdacf9fc9b"},
qty: 75, 
tags: ["blank", "red"],
dim_cm: [ 22.85, 30 ] },
```

2. only return the specified field
`db.collection.find({}, {item: 1 })`
would return
``` {
_id: {$oid: "f58d5989-83aa-481c-93b4-f5fdacf9fc9b"},
item: "planner", 
```

3) you cannot match including and excluding in the projection object

the find function shout have the params
`db.collection.find({}:SearchCriteria,{}: Projections,{}: FindOptions)`

If this is already possible with this package at this point, please educate me or add an example to the README.

Thanks!

**Comment by hackers267** [comment]
You can use the 0.20 to support the projection;
like
```
db.collection.findOne( { }, { projection : { _id : 0 , name : 1 } } )
```
