### ISSUE TITLE
Support $inc 

### ISSUE THREAD

**Issue by YuriyTigiev** [manyuanrong/deno_mongo#132]
Does the deno_mongo support $inc?

```
await User.updateOne({ _id: ObjectId(id) }, {
      $set: {
        name,
        role,
        isDisabled,
        updatedAt,
      },
      $inc: {doc_version, 1},
    }
```

**Comment by manyuanrong** [comment]
It should be possible

**Comment by YuriyTigiev** [comment]
Returns error 

```
  /**
   * Update user service
   * @param id
   * @param options
   * @returns Promise<UpdatedStructure | Error> Returns Updated acknowledgement
   */
  public static async updateUser(
    id: string,
    options: UpdateUserStructure,
  ): Promise<UpdatedStructure | Error> {
    const user: (UserSchema | null) = await User.findOne({ _id: ObjectId(id) });
    if (!user) {
      log.error("User not found");
      return throwError({
        status: Status.NotFound,
        name: "NotFound",
        path: "user",
        param: "user",
        message: `User not found`,
        type: "NotFound",
      });
    }
    const { doc_version } = user;
    const { isDisabled, name, role } = options;
    const updatedAt = new Date();
    const result: ({
      matchedCount: number;
      modifiedCount: number;
      upsertedId: ObjectId | null;
    }) = await User.updateOne({ _id: ObjectId(id) }, {
      $set: {
        name,
        role,
        isDisabled,
        updatedAt,
      },
      $inc: {doc_version, 1},
    },
    );
    if(result){
      const user_history: ObjectId = await UserHistory.insertOne(
        {id:ObjectId(id) , name, role, isDisabled, doc_version: doc_version + 1},
      );
    }
    else {
      return throwError({
        status: Status.BadRequest,
        name: "BadRequest",
        path: "user",
        param: "user",
        message: `Could not update user`,
        type: "BadRequest",
      });
    }

    return result;
  }

```


```
C:\Users\yuriy\.deno\bin\deno.exe run --inspect-brk=127.0.0.1:9229 --allow-all --unstable .\app.ts
Debugger listening on ws://127.0.0.1:9229/ws/7e8db991-71b8-41ed-93d6-ac1e4ef21c9e
Check file:///C:/Users/yuriy/source/repos/deno_rest/app.ts
error: TS1005 [ERROR]: ':' expected.
      $inc: {doc_version, 1},
                           ^
    at file:///C:/Users/yuriy/source/repos/deno_rest/services/user.service.ts:103:28

TS2345 [ERROR]: Argument of type '{ $set: { name: string | undefined; role: string | undefined; isDisabled: boolean | undefined; updatedAt: Date; }; $inc: { doc_version: any; 1: any; }; }' is not assignable to parameter of type 'FilterType<UserSchema>'.
  Object literal may only specify known properties, and '$inc' does not exist in type 'FilterType<UserSchema>'.
      $inc: {doc_version, 1},
```

**Comment by manyuanrong** [comment]
It is supported by itself, but the type check fails. The temporary solution is to use any

**Comment by hackers267** [comment]
> 
> 
> Returns error
> 
> ```
>   /**
>    * Update user service
>    * @param id
>    * @param options
>    * @returns Promise<UpdatedStructure | Error> Returns Updated acknowledgement
>    */
>   public static async updateUser(
>     id: string,
>     options: UpdateUserStructure,
>   ): Promise<UpdatedStructure | Error> {
>     const user: (UserSchema | null) = await User.findOne({ _id: ObjectId(id) });
>     if (!user) {
>       log.error("User not found");
>       return throwError({
>         status: Status.NotFound,
>         name: "NotFound",
>         path: "user",
>         param: "user",
>         message: `User not found`,
>         type: "NotFound",
>       });
>     }
>     const { doc_version } = user;
>     const { isDisabled, name, role } = options;
>     const updatedAt = new Date();
>     const result: ({
>       matchedCount: number;
>       modifiedCount: number;
>       upsertedId: ObjectId | null;
>     }) = await User.updateOne({ _id: ObjectId(id) }, {
>       $set: {
>         name,
>         role,
>         isDisabled,
>         updatedAt,
>       },
>       $inc: {doc_version, 1},
>     },
>     );
>     if(result){
>       const user_history: ObjectId = await UserHistory.insertOne(
>         {id:ObjectId(id) , name, role, isDisabled, doc_version: doc_version + 1},
>       );
>     }
>     else {
>       return throwError({
>         status: Status.BadRequest,
>         name: "BadRequest",
>         path: "user",
>         param: "user",
>         message: `Could not update user`,
>         type: "BadRequest",
>       });
>     }
> 
>     return result;
>   }
> ```
> 
> ```
> C:\Users\yuriy\.deno\bin\deno.exe run --inspect-brk=127.0.0.1:9229 --allow-all --unstable .\app.ts
> Debugger listening on ws://127.0.0.1:9229/ws/7e8db991-71b8-41ed-93d6-ac1e4ef21c9e
> Check file:///C:/Users/yuriy/source/repos/deno_rest/app.ts
> error: TS1005 [ERROR]: ':' expected.
>       $inc: {doc_version, 1},
>                            ^
>     at file:///C:/Users/yuriy/source/repos/deno_rest/services/user.service.ts:103:28
> 
> TS2345 [ERROR]: Argument of type '{ $set: { name: string | undefined; role: string | undefined; isDisabled: boolean | undefined; updatedAt: Date; }; $inc: { doc_version: any; 1: any; }; }' is not assignable to parameter of type 'FilterType<UserSchema>'.
>   Object literal may only specify known properties, and '$inc' does not exist in type 'FilterType<UserSchema>'.
>       $inc: {doc_version, 1},
> ```

Where you use `$inc` should be `$inc: { doc_version: 1}` not `$inc: { doc_version, 1}`
