### ISSUE TITLE
Uncaught Assertion Error | v0.20.0

### ISSUE THREAD

**Issue by hugovisk** [manyuanrong/deno_mongo#133]
```terminal
$ deno --version
deno 1.5.4 (bc79d55, release, x86_64-unknown-linux-gnu)
v8 8.8.278.2
typescript 4.0.5
```
------------------------
### _db.ts_
```typescript
import { MongoClient } from "https://deno.land/x/mongo@v0.20.0/mod.ts";

const client = new MongoClient();
client.connect('mongodb://localhost:27017');

const db = client.database('test');
```
-------------------------
```terminal
$ deno run --allow-net --allow-read --allow-write --allow-plugin --allow-env --unstable db.ts
Check file:///workspace/db.ts
error: Uncaught AssertionError
    throw new AssertionError(msg);
          ^
    at assert (asserts.ts:152:11)
    at MongoClient.database (client.ts:48:5)
    at db.ts:6:19
```

**Comment by hackers267** [comment]
hello,the resolve is to use
```
const await client.connect('mongodb://localhost:27017');
```

**Comment by hugovisk** [comment]
Hi there! You are right the await resolved.

Thanks a lot :D

**Comment by chansdad** [comment]
If I change that line to use await , i am seeing the previous line throw error in vs code " Cannot redeclare block scoped variable"

**Comment by hugovisk** [comment]
hi,
this solved for me
import { MongoClient } from "https://deno.land/x/mongo@v0.20.0/mod.ts";

const client = new MongoClient();
await client.connect('mongodb://localhost:27017');

const db = client.database('test');

export default db

Also there is an connection test file in the repo that you can check:
https://github.com/manyuanrong/deno_mongo/blob/refactor/tests/connect.test.ts

Best regards



Em ter., 15 de dez. de 2020 às 17:00, chansdad <notifications@github.com>
escreveu:

**Comment by hackers267** [comment]
It didn't surpport localhost try 127.0.0.1, the bug may caused by deno in window

**Comment by PabloHdzVizcarra** [comment]
> hello,the resolve is to use
> 
> ```
> const await client.connect('mongodb://localhost:27017');
> ```

thanks men, salved my life

**Comment by hackers267** [comment]
> 
> 
> > hello,the resolve is to use
> > ```
> > const await client.connect('mongodb://localhost:27017');
> > ```
> 
> thanks men, salved my life

Did you use the win os? If true, you can try 127.0.0.1 to replace the ‘localhost'.
