### ISSUE TITLE
Passing undefined to findOne({_id: undefined}) returns the first item in db

### ISSUE THREAD

**Issue by Kylescottw** [manyuanrong/deno_mongo#134]
As mentioned in the title
`const user1 = await users.findOne({ _id: undefined });`
will return the first item in the db

**Comment by manyuanrong** [comment]
The undefined field is ignored. You can try to set options. ignoreUndefined=false
```ts
const user1 = await users.findOne({ _id: undefined },{ignoreUndefined:false});
```

**Comment by Kylescottw** [comment]
Thank you for the reply.
the command line returns 
Argument of type '{ ignoreUndefined: boolean; }' is not assignable to parameter of type 'FindOptions'.

**Comment by manyuanrong** [comment]
Are you using v0.20.0, if there is a problem with v0.20.0. You can try:
```ts
await users.findOne( { _id: {$exists: false}})
```

**Comment by hackers267** [comment]
> 
> 
> As mentioned in the title
> `const user1 = await users.findOne({ _id: undefined });`
> will return the first item in the db

What you want to do? To find item which _id is "undefined" or a item which didn't include _id;

**Comment by manyuanrong** [comment]
@Kylescottw Has your problem been resolved?

**Comment by Kylescottw** [comment]
Hi I have not tried v0.20.0,
I am using https://deno.land/x/mongo@v0.13.0/mod.ts

As i said passing undefined 
`const user1 = await users.findOne({ _id: undefined });`
will return the first item in the db.

the expected behavior is that passing  `{ _id: undefined }` to findOne should not return the first item in the db.
All items in the db have a defined _id

**Comment by Kylescottw** [comment]
We can close the ticket, 
I did not know the undefined field is ignored. 
So essentially passing `findOne({ _id: undefined })` is the same as `findOne()`. 

Thank you for your time.
