### ISSUE TITLE
cache this plugin in docker build

### ISSUE THREAD

**Issue by sqllyw** [manyuanrong/deno_mongo#136]
hi,
when run a docker image , always got this:
````
INFO downloading deno plugin "deno_mongo" from "https://github.com/manyuanrong/deno_mongo/releases/download/v0.13.0/libdeno_mongo.so"
````
is there a way to cache this file in the container during building the docker image? thanks

**Comment by hackers267** [comment]
Which version did you use? Try 0.20.0?

**Comment by sqllyw** [comment]
you are right, tried 0.20, no more downloading, what's the difference here?

**Comment by sqllyw** [comment]
with v0.20.0, there is no need to download mongo_3bbff9a1cd76f3d988b3ca28c7163c3f.so file, but some other issues comes out:
````
 Uncaught (in promise) Error: failed to lookup address information: Name or service not known
    at processResponse (core.js:223:11)
    at Object.jsonOpAsync (core.js:240:12)
    at async Object.connect (deno:cli/rt/30_net.js:224:13)
    at async MongoClient.connect (client.ts:20:18)
    at async Mongo.connect (mongo.ts:19:9)
    at async mongo.ts:13:1

````

**Comment by hackers267** [comment]
> 
> 
> you are right, tried 0.20, no more downloading, what's the difference here?

The 0.20.0 use the TS to refactor the client, didn't use the rust plugin.

**Comment by hackers267** [comment]
> 
> 
> with v0.20.0, there is no need to download mongo_3bbff9a1cd76f3d988b3ca28c7163c3f.so file, but some other issues comes out:
> 
> ```
>  Uncaught (in promise) Error: failed to lookup address information: Name or service not known
>     at processResponse (core.js:223:11)
>     at Object.jsonOpAsync (core.js:240:12)
>     at async Object.connect (deno:cli/rt/30_net.js:224:13)
>     at async MongoClient.connect (client.ts:20:18)
>     at async Mongo.connect (mongo.ts:19:9)
>     at async mongo.ts:13:1
> ```

What's the way you use the `connect` method?

**Comment by sqllyw** [comment]
await client.connect(dburl)

**Comment by hackers267** [comment]
> 
> 
> await client.connect(dburl)

What's the content of dburl?

**Comment by sqllyw** [comment]
something similar to this:

"mongodb+srv://sample:sample@cluster0.ex123.mongodb.net/sample?retryWrites=true&w=majority"

**Comment by hackers267** [comment]
> 
> 
> something similar to this:
> 
> "mongodb+srv://sample:[sample@cluster0.ex123.mongodb.net](mailto:sample@cluster0.ex123.mongodb.net)/sample?retryWrites=true&w=majority"

The mongo_deno did't support the `mongodb+srv` protocol now!

**Comment by sqllyw** [comment]
I see, so I tried this in nodejs and it works:
````

var uri = "mongodb://user123:password123@cluster0-shard-00-00.ex9tq.mongodb.net:27017,cluster0-shard-00-01.ex9tq.mongodb.net:27017,cluster0-shard-00-02.ex9tq.mongodb.net:27017/mydb?ssl=true&replicaSet=atlas-hr3klt-shard-0&authSource=admin&retryWrites=true&w=majority";
````
then I use the same uri to test on deno mongo 0.20, but got this:
````
error: Uncaught TypeError: Invalid URL.
    at new URL (deno:op_crates/web/11_url.js:722:15)
    at parse (uri.ts:5:21)
    at MongoClient.connect (client.ts:15:19)
    at test1.ts:8:14

````

**Comment by manyuanrong** [comment]
V0.20.0 does not support parsing complex uri now, you need to keep it simple. Also, user authorization is not currently supported. That is to say, your mongodb server needs to set a blank password and ensure security by restricting ip. Or you can continue to use the previous version, and write a separate prepare.ts, and introduce https://deno.land/x/mongo@xxx/mod.ts, and execute the file in advance in your dockerfile, and finally Then package the cached .deno_plugins directory into the image correctly

**Comment by sqllyw** [comment]
> V0.20.0 does not support parsing complex uri now, you need to keep it simple. Also, user authorization is not currently supported. That is to say, your mongodb server needs to set a blank password and ensure security by restricting ip. Or you can continue to use the previous version, and write a separate prepare.ts, and introduce https://deno.land/x/mongo@xxx/mod.ts, and execute the file in advance in your dockerfile, and finally Then package the cached .deno_plugins directory into the image correctly

Thanks for the info, for now I'll go back to 0.13 as it's a working version, the plug in added 14mb in size, while v.20 does not have too much overhead, will go back in the future,keep up the good work, thanks again
