### ISSUE TITLE
findOne by ObjectId does not work

### ISSUE THREAD

**Issue by ErnieBernie10** [manyuanrong/deno_mongo#138]
I have this code 
```ts
const id = ctx.params.id;
const person = await people.findOne({
  _id: id
});
```

id is an ObjectId as string. I want to receive the person with the ObjectId provided, but this code returns undefined. 

Other things I've tried:

```ts
const person = await people.findOne({
  _id: {
    $oid: id
  }
});
```

Using
```
Deno: 1.5.4
deno_mongo: 0.20.0
```

**Comment by vorticalbox** [comment]
This will likely be because your are matching a string rather than a ObjectID.

Node has a bson library that has a conversation https://github.com/mongodb/js-bson/blob/master/src/objectid.ts 

Could implement then using deno standard library but it would be nice to have bson in the standard libary

**Comment by vorticalbox** [comment]
It will be matching on a string rather than an object Id, you should be about to use the bson export to convert the string into an objectID.

**Comment by ErnieBernie10** [comment]
I was also thinking, but Bson isn't exported from mod.ts so I don't have access to it.

**Comment by hackers267** [comment]
> 
> 
> It will be matching on a string rather than an object Id, you should be about to use the bson export to convert the string into an objectID.

If you want to use the `ObjectId`, you can use like that:

```
import { ObjectId } from "https://deno.land/x/mongo@v0.20.0/bson/mod.ts";

const id = new ObjectId(ctx.params.id);
const person = await people.findOne({
  _id: id
});

```

**Comment by ErnieBernie10** [comment]
Right this worked. Thanks!

Maybe it would be a good idea to include ObjectId as an export of the main mod.ts, but I don't know what convention this lib is using.
