### ISSUE TITLE
Module '"https://deno.land/x/mongo@v0.20.0/mod"' has no exported member 'Database'

### ISSUE THREAD

**Issue by Boyceman** [manyuanrong/deno_mongo#143]
hey you guys, i wanna know why you change your mind to cancel export Database class? Are there any concerns?

**Comment by eveningkid** [comment]
Hi,

You can actually import it even though it wasn't exported from `mod.ts`:

```js
import { Database } from "https://deno.land/x/mongo@v0.20.0/src/database.ts";
```
