### ISSUE TITLE
Missing $push feature from MongoDB

### ISSUE THREAD

**Issue by hoangtranson** [manyuanrong/deno_mongo#148]
I have read document on mongodb about $push and look like we are missing this operator.
Do we have any plan to add it to library?

ref: https://docs.mongodb.com/manual/reference/operator/update/push/

**Comment by manyuanrong** [comment]
It should be supported. Have you tried it and got unsupported error feedback?

**Comment by hoangtranson** [comment]
Hi @manyuanrong, 

Here is what I saw in visual studio code. As u see, I can find `$push` in the autocomplete.

![push](https://user-images.githubusercontent.com/35447677/101986568-83aa4800-3cc9-11eb-9d96-dad1ff78b5f1.png)

**Comment by manyuanrong** [comment]
It looks like you are continuing to use the old version before the refactoring, preferably the latest
