### ISSUE TITLE
error: TS2694 [ERROR]: Namespace 'Deno' has no exported member 'PluginOp'.

### ISSUE THREAD

**Issue by mooniitt** [manyuanrong/deno_mongo#15]
use deno v1.0.0 
get a problem like this error

**Comment by manyuanrong** [comment]
Are you using the latest mongo@v0.6.0?

**Comment by rikyperdana** [comment]
Found the very same problem here
![Screenshot from 2020-05-14 17 03 20](https://user-images.githubusercontent.com/11875540/81921535-fb65a680-9604-11ea-9d61-f0d221d8074f.png)

**Comment by manyuanrong** [comment]
~~import { init, MongoClient } from "https://deno.land/x/mongo@v0.5.2/mod.ts";~~

use this:

```ts
import { init, MongoClient } from "https://deno.land/x/mongo@v0.6.0/mod.ts";
```
