### ISSUE TITLE
Segmentation fault on Ubuntu 18.04 WSL 2

### ISSUE THREAD

**Issue by sudeepgumaste** [manyuanrong/deno_mongo#22]
INFO load deno plugin "deno_mongo" from local "/mnt/d/projects/deno-crud/.deno_plugins/deno_mongo_90b8202cc9554c64927ac1e194abc3f6.so"
Segmentation fault (core dumped)

Running with command
deno run --allow-net --allow-write --allow-read --allow-plugin --unstable server.ts

File
import { init, MongoClient } from "https://deno.land/x/mongo@v0.6.0/mod.ts";

// Initialize the plugin
await init();

const client = new MongoClient();
client.connectWithUri("mongodb://localhost:27017");

const db = client.database("test");
const users = db.collection("users");

// insert
const insertId = await users.insertOne({
    username: "user1",
    password: "pass1"
});

**Comment by manyuanrong** [comment]
Confirm that the problem only occurs on Ubuntu 18.04 WSL 2?
And whether Deno's version is v1.0.0

**Comment by sudeepgumaste** [comment]
My sincere apologies. I was on deno-rc1

**Comment by micktaiwan** [comment]
Same pb
- Ubuntu 20.04
- Deno 1.0.2
