### ISSUE TITLE
Handeling errors for invalid mongo id

### ISSUE THREAD

**Issue by subhrapaladhi** [manyuanrong/deno_mongo#23]
When I try to use updateOne or findOne for invalid mongo id. It is throwing the error shown in the image and crashing the server program. I am totally new to Deno. How can I handle this error? Any kind of help will be appreciated.
Here is my the part of code for findOne
```

import {Friend} from '../helpers/dbconnect.ts';

export const getFriend: any = async(context: any)=> {
    try{
        let id: string = context.params.id;

        const data :any = await Friend.findOne({_id: {"$oid": id}});    
        if(data){
            context.response.body = data;
            context.response.status = 200;    
        } else {
            context.response.body = "not found";
            context.response.status = 204; 
        }
    }
    catch(e) {
        context.response.body = null;
        context.response.status = 500
        console.log(e);
    }
}

```
![Screenshot from 2020-05-16 20-00-11](https://user-images.githubusercontent.com/39485981/82122228-df523880-97af-11ea-91bd-098dc7783196.png)

**Comment by manyuanrong** [comment]
It looks like the incoming ObjectId is invalid. Can you confirm that the ID is correct?
And about the _id field, you can use the ObjectId constructor to create:
```ts
import {ObjectId} from "https://deno.land/x/mongo@v0.6.0/mod.ts";
// ...
const doc = await collection.findOne ({_ id: ObjectId ("xxxxxxx")});
```

**Comment by subhrapaladhi** [comment]
Yes, the ObjectId is invalid. 
I want to know how can we handle the error if invalid ObjectId is used. I don't want such errors to crash the server.

**Comment by manyuanrong** [comment]
ObjectId's correctness verification is placed in the TS side. If you use the ObjecId constructor, you can catch the error. If you do it on the Rust side, you have to deal with tedious error mapping

**Comment by subhrapaladhi** [comment]
Thanks a lot for the information. I will keep these things in mind. :)
