### ISSUE TITLE
insertOne() panicks when trying to send a duplicate index

### ISSUE THREAD

**Issue by nickpersad** [manyuanrong/deno_mongo#26]
I tried inserting a record that already exists in Mongo and it panicked and didn't send the error correctly back to Deno.

```thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: WriteError(WriteError(WriteError{ code: 11000, code_name: None, message: "E11000 duplicate key error collection: test.users index: id_1 dup key: { id: null}" })) }', src/command/insert.rs:32:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by ATakaSKY** [comment]
Exactly the same error is happening if I delete a document and try deleting it again.

<img width="869" alt="Screenshot 2020-05-24 at 12 40 17 PM" src="https://user-images.githubusercontent.com/17201629/82747966-bcc9ac00-9dbb-11ea-9b40-b585aa41c123.png">

**Comment by SreeniIO** [comment]
Same issue when trying to insert a duplicate _id with insertMany()

```sh
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: 
BulkWriteError(BulkWriteFailure { write_errors: Some([BulkWriteError { index: 0, code: 11000, code_name: None, 
message: "E11000 duplicate key error collection: ***** index: _id_ dup key: { : \"243ebf3d-c687-4984-8f51-
f4e6a3b7f42e\" }" }]), write_concern_error: None }) }', src/command/insert.rs:50:29
```
