### ISSUE TITLE
Error while running deno run command

### ISSUE THREAD

**Issue by ATakaSKY** [manyuanrong/deno_mongo#27]
I am getting the following error while running the code with : `deno run --allow-net --allow-write --allow-read --allow-plugin --unstable deno-mongo.ts`

<img width="675" alt="Screenshot 2020-05-19 at 12 33 01 PM" src="https://user-images.githubusercontent.com/17201629/82295261-1d787380-99cd-11ea-925f-3e0c7bec2b0c.png">

**Comment by imabhishekkumar** [comment]
Try initializing MongoClient like this: 
`import { init, MongoClient } from "https://deno.land/x/mongo@v0.6.0/mod.ts";

await init();`

**Comment by imabhishekkumar** [comment]
Try initializing MongoClient like this:
`import { init, MongoClient } from "https://deno.land/x/mongo@v0.6.0/mod.ts";`
`await init()`

**Comment by manyuanrong** [comment]
With v0.7.0, there is no need to manually call init
