### ISSUE TITLE
add promises or callbacks after method executes (insert,insertOne,find,findOne)

### ISSUE THREAD

**Issue by WhoAdarshPandya** [manyuanrong/deno_mongo#31]
Hey, Thanks for making amazing library , my doubt is , is there a way to know that the query you fired is successful / gets error in methods (insert ,update ,delete,find) through promises or callbacks

**Comment by dimitriskoslek** [comment]
`const { matchedCount, modifiedCount, upsertedId } = await users.updateMany(....)`
you can work with the variables `matchedCount` `modifiedCount` `upsertedId` for example.
Doesn't seem to return a promise but the result variables.
