### ISSUE TITLE
distinct Implementation

### ISSUE THREAD

**Issue by lraphael** [manyuanrong/deno_mongo#38]
Is there any way to use collection.distinct()?

**Comment by alirealasad** [comment]
well, we do need the collection.distinct() feature though but for the moment you can use it in this way.

`//first import lodash 
import _ from "https://deno.land/x/deno_lodash/mod.ts";

// where $match will be your query object
// and $project be your distinct property (0 for removing properties and 1 for including properties).
// note:- you desired property should be on $project
const emails = await users.aggregate([{ $match: {}}, { $project: { email: 1, _id: 0 }} ]);

//then use the lodash uniqBy method to get the unique values.
_.uniqBy(users ,function(e:any) {
    return e.email
  })

//and then use the .map extract the values if you want.
const mails = emails.map(function(e){
   return e.email
}

console.log("all the unique mails", mails); 
 //-> log all distinct mails


`
hope that solves your problem if not you can add more.

links:-
https://lodash.com/docs/4.17.15#uniqBy
https://stackoverflow.com/questions/31740155/lodash-remove-duplicates-from-array
https://docs.mongodb.com/manual/reference/operator/aggregation/project/
