### ISSUE TITLE
no limitation when find({ }) returns multiple childs

### ISSUE THREAD

**Issue by arthur-spa** [manyuanrong/deno_mongo#42]
The function .limit() will be nice to add, to limit the number of results. Like the mongoose one. Thanks.

**Comment by alirealasad** [comment]
use $limit 
`https://docs.mongodb.com/manual/reference/operator/aggregation/limit/`

**Comment by arthur-spa** [comment]
Thank you ! So I close the issue.

**Comment by arthur-spa** [comment]
Sorry to ask again but how should I add the `$limit` ? If i add it at the end of my query `.find({ xxx }).limit( x )`, it throws a typescipt error. I'can't figure out where to place it in my find request. This is my entire query code : `.find({
      loca: {
        $near: {
          $geometry: { type: "Point", coordinates: co },
          $maxDistance: r,
        },
      },
    });`
Thanks again.

**Comment by alirealasad** [comment]
aggregation in` .find` isn't working so  use `.aggregate` instead

`.aggregate([{$match:{ loca: { $near: { $geometry: { type: "Point", coordinates: co }, $maxDistance: r, }, }, }},{$limit:2}])`

**Comment by arthur-spa** [comment]
You're the best ! Thanks again.
