### ISSUE TITLE
Rust panic

### ISSUE THREAD

**Issue by dimitriskoslek** [manyuanrong/deno_mongo#44]
Hello. I didn't touch my previously compiled and running code and I have an error on deno run, seemingly happens while loading the plugin and so it appears from the backtrace, I pasted it here: https://pastebin.com/S7VNTP3P

Edit:
deno 1.0.4 | v8 8.4.300 | typescript 3.9.2

**Comment by Wellington01** [comment]
I am also trying to use version 0.7.0 and is giving the same problem as above, I have version 1.0.4 of deno

**Comment by IktaS** [comment]
Same problem, I think it broke on deno version 1.0.4, I recommend reverting to temporarily fix the issue

**Comment by dimitriskoslek** [comment]
I tried going back to 1.0.3 but it was still a problem. @Wellington01 was 1.0.0 the latest that worked?

**Comment by peterdee** [comment]
Having the same issue with Deno 1.0.5, version 1.0.0 and 1.0.1 worked fine.

Full log:
```text
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/command/connect.rs:63:24
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: deno_mongo::command::connect::connect_with_uri
  10: deno_mongo::op_command
  11: <deno::ops::plugin::PluginInterface as deno_core::plugin_api::Interface>::register_op::{{closure}}
  12: deno_core::core_isolate::CoreIsolateState::dispatch_op
  13: deno_core::bindings::send
  14: <extern "C" fn(A0) .> R as rusty_v8::support::CFnFrom<F>>::mapping::c_fn
  15: _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
  16: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  17: _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
start.sh: line 1: 32462 Abort trap: 6           deno run --reload --allow-env --allow-net --allow-read --allow-write --allow-plugin --unstable main.ts
```

**Comment by Wellington01** [comment]
> I tried going back to 1.0.3 but it was still a problem. @Wellington01 was 1.0.0 the latest that worked?

I only tested it in version 1.0.0, because it was the one I had tested previously and everything went well.

**Comment by arthur-spa** [comment]
More over the new deno 1.1.0 release didn't fix it. Still have the error.

**Comment by musti-91** [comment]
I'm having this error too. any fix?

**Comment by peterdee** [comment]
I don't have any issues with `Deno` v1.1.0 and `deno_mongo` v0.8.0.

Check your `deno_mongo` version, update it to v0.8.0 and reload your cache.

**Comment by arthur-spa** [comment]
You're right ! Works for me.

**Comment by Arekcze** [comment]
I am still having this issue, despite using `deno_mongo` v0.8.0 and `Deno` v1.1.0. As a database I have tried to use mongo atlas.

**Comment by dimitriskoslek** [comment]
This worked for me with a local mongo installation, on deno 1.1 and mongo_deno 0.8.

**Comment by dimitriskoslek** [comment]
If it works for others too we can close this one I guess.
