### ISSUE TITLE
How to join two table with aggregate ?

### ISSUE THREAD

**Issue by berkekurnaz** [manyuanrong/deno_mongo#45]
I try to join two collections with aggregate but I didn't. My sample code is here:

> const result = await articles.aggregate([
    {
      $lookup: {
        from: "authors",
        localField: "oid",
        foreignField: "author_id",
        as: "author",
      },
    },
    {
      $unwind: "$author",
    },
  ]);
  req.send(result);

I want an output like the one below. But for now, although there are only 3 Articles in my database, it matches these authors with all authors and brings a total of 6 records.

[My Output](https://i.stack.imgur.com/APQHt.png)

I think the problem is caused by the following reason. But I'm not sure.

> // My output id format
"_id": {
      "$oid": "5ed7abfc00f94b9c0048ba5e"
},

> // what will be written in the localfield field in this section
$lookup: {
        from: "authors",
        localField: "oid",
        foreignField: "author_id",
        as: "author",
},

How can i solve this problem? I am waiting your help.

**Comment by iamfourh2e** [comment]
I think the problem was that you save _id as an object _id but inside the lookup pipeline, it only supports string. so my suggestion is to store _id as a hash string

**Comment by berkekurnaz** [comment]
I use these codes for now but these codes not good for performance.

> var result = await articles.find();
  for(var i=0; i<result.length; i++){
    result[i].author = await authors.findOne({ _id: { $oid: result[i].author_id } });
  }
  req.send(result);

**Comment by manyuanrong** [comment]
Now we will not do too much operation on the _id field, and will maintain an original state, so the problem may have been resolved
