### ISSUE TITLE
Support for sort?

### ISSUE THREAD

**Issue by johnsonsamuel** [manyuanrong/deno_mongo#48]
### What is this about?

Do we have support for find and sort?

Thanks :)

**Comment by alirealasad** [comment]
use the $sort operator with aggregate
https://docs.mongodb.com/manual/reference/operator/aggregation/sort/

hope that solves your problem.

**Comment by GuilhermeVendramini** [comment]
Alternative solution:

```
  async find(): Promise<[]> {
    let result = await data.find();

    if (result) {
      return result.sort((d1: any, d2: any) => {
        if (d1.updated > d2.updated) {
          return -1;
        }
        if (d1.updated < d2.updated) {
          return 1;
        }
        return 0;
      });
    }

    return [];
  },
```

**Comment by romaklimenko** [comment]
> result.sort((d1: any, d2: any)

This is a client-side sorting. Same results (probably), but fundamental difference.
