### ISSUE TITLE
Find with "fields" list?

### ISSUE THREAD

**Issue by richcorbs** [manyuanrong/deno_mongo#49]
Is it possible to send a fields object to `find` to get back a subset of attributes?

The mongo command-line client takes a second argument like this:

`db.records.find({}, {_id: 0, column1: 1, column2: 1})`

Is this possible in deno_mongo?

**Comment by manyuanrong** [comment]
At present,`project` operation can only use`aggregate`

**Comment by alirealasad** [comment]
try using this 
`db.records.aggregate([{$match:{}}, {$project:{_id: 0, column1: 1, column2: 1}}]);`
where $match  will be your query and $project will be your fields.

**Comment by richcorbs** [comment]
Thanks! That worked. Still learning mongo.
