### ISSUE TITLE
add db.collection.distinct() feature

### ISSUE THREAD

**Issue by alirealasad** [manyuanrong/deno_mongo#50]
hi, I'm creating a Mongoose like ODM built top of this library. I successfully added nearly all methods except for the `distinct` method can you please add that method. 

https://docs.mongodb.com/manual/reference/method/db.collection.distinct/

this issue is also mentioned in  [#38 ](https://github.com/manyuanrong/deno_mongo/issues/38) 
I fork this repo and tried to add that feature by myself but failed to do so that because I'm a beginner to rust.

I hope you add this feature.

and also version 0.8.0 doesn't seem to work on windows.

**Comment by divy-work** [comment]
@alirealasad Looks like #82 is what you want :smile:
