### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by lucarducci** [manyuanrong/deno_mongo#51]
`Thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: ServerSelectionError { message: "Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: localhost:27017, Type: Unknown, Error: failed to fill whole buffer }, ] }" } }'`

Is it due to an old version of MongoDB? I'm using the 3.4.9

**Comment by alirealasad** [comment]
no, I don't think the version is the issue here. 

& if you are doing any complex queries then use `.aggregate` because the other methods are not that stable.

**Comment by lucarducci** [comment]
It is an easy find query, the same code works with a newer version of
mongodb.

The only difference is the connection string, could maybe be that?

**Comment by alirealasad** [comment]
wait connection string well deno_mongo doesn't support connection string though you have to connect manually by doing this:- 

```ts
import { MongoClient } from "https://deno.land/x/mongo@v0.8.0/mod.ts";

const client = new MongoClient();
client.connectWithUri("mongodb://localhost:27017");

const db = client.database("test");
const users = db.collection("users");
```

more about that here  [#41](https://github.com/manyuanrong/deno_mongo/issues/41)

**Comment by lucarducci** [comment]
This is what I was trying, it works if I insert the connection URL to ATLAS:
`mongodb+srv://myuser:mypwd@cluster0-bo2mg.mongodb.net/mydbname?retryWrites=true&w=majority`

**Comment by lucarducci** [comment]
Here an example of the issue also with a new version of mongodb:

https://github.com/lucarducci/deno-mongo-debug

Run with:
docker-compose up

If I use an ATLAS connection string it works. Not with a local db or from docker.

**Comment by lucarducci** [comment]
Any update on this issue?

**Comment by lucacasonato** [comment]
Can you try with MongoDB 4.0 or 4.2? Also make sure the links in your docker-compose are set up correctly. `localhost:27017` might not be the correct address to communicate with your MongoDB cluster in a different container.
