### ISSUE TITLE
All v6, v7 and v8 are broke

### ISSUE THREAD

**Issue by rikyperdana** [manyuanrong/deno_mongo#61]
Here is the error for v6
![error 0 6 0](https://user-images.githubusercontent.com/11875540/85936281-52a8a780-b923-11ea-9add-40f5b96efe5d.png)

And here is the error for both v7 and v8
![error 0 8 0](https://user-images.githubusercontent.com/11875540/85936286-66540e00-b923-11ea-96b0-03be0be2a783.png)

Here is my sample repo if you'd care to look
https://github.com/rikyperdana/deno-crud

**Comment by amatiasq** [comment]
I can confirm

**Comment by amatiasq** [comment]
I had this issue with v7 but v8 works for me

**Comment by divy-work** [comment]
This is most probably because of your deno version not compatible with the version used by deno_mongo.

Try using deno v1.2.0 with latest deno_mongo version.

**Comment by divy-work** [comment]
This is most probably because of your deno version not compatible with the version used by deno_mongo.

Try using deno v1.2.0 with latest deno_mongo version.
