### ISSUE TITLE
SelectionCriteria is missing on find query

### ISSUE THREAD

**Issue by kevinhassan** [manyuanrong/deno_mongo#62]
Hi 😄! 
I wanted to excluded some attribute on my find() Mongodb query but I can't. 
Indeed, On your `find()` implementation, I didn't found the `selectionCriteria` (only `filter` & `findOptions` are provided).

Mongodb documentation : [here](https://docs.mongodb.com/manual/tutorial/project-fields-from-query-results/#return-all-but-the-excluded-fields)

Mongo rust driver `find() implementation` : [here](https://github.com/mongodb/mongo-rust-driver/blob/master/src/operation/find/mod.rs)

**Comment by manyuanrong** [comment]
Now you can achieve this through projection
```ts
db.collection.findOne( { }, { projection : { _id : 0 , name : 1 } } )
```
