### ISSUE TITLE
DeleteOne crash the app on some cases

### ISSUE THREAD

**Issue by TomPradat** [manyuanrong/deno_mongo#65]
I tried something like : 

```js
await db.collection('todos').deleteOne({ _id: { $oid: "a" }});
```

And got my program to crash with the following error : 

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: FromHexError(OddLength)', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/bson-0.14.1/src/bson.rs:575:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by lucacasonato** [comment]
An object ID must be a hexadecimal string made up of couples of the characters `0123456789abcdef`. The amount of characters must thus be even. If this is not the case deno_mongo will panic.

**Comment by manyuanrong** [comment]
> await db.collection('todos').deleteOne({ _id: { $oid: "a" }});

You should try to use `ObjectId("id")` instead of `{$oid:"id"}`
TS does a check on it and throws a catchable exception to avoid panic in rust

**Comment by TomPradat** [comment]
Alright, I'll try that 👍 

Though I think it would be better to throw an Error than crash the program here.

**Comment by avudaiappan-cse** [comment]
```
import { ObjectId } from "https://deno.land/x/mongo@v0.8.0/mod.ts";

 if (ObjectId("a")) {
await db.collection('todos').deleteOne({ _id: { $oid: "a" }});
}

```

First check the $oid with ObjectId function then proceed your operation.
ObjectId function returns if it is a valid Object ID
false if it is invalid

Its worked for me. I hope it works you too!
