### ISSUE TITLE
Provide musl builds

### ISSUE THREAD

**Issue by lucacasonato** [manyuanrong/deno_mongo#66]
AWS Lambda uses a Linux distribution called amazonlinux2 that uses [musl](https://musl.libc.org/) instead of glibc. It would be great if deno_mongo would provide fully static builds that do not dynamically link to the libc provided by the os, so the plugin can be used on AWS Lambda. This is very simple to do in Rust: https://doc.rust-lang.org/edition-guide/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.html

If this seems reasonable I can create a PR for this.

**Comment by manyuanrong** [comment]
welcome
