### ISSUE TITLE
Generate ObjectId

### ISSUE THREAD

**Issue by aliddy23** [manyuanrong/deno_mongo#67]
It'd be great if there were some way to generate an ObjectId. If there is, please show me how.

Thanks

**Comment by manyuanrong** [comment]
https://cdn.pika.dev/bson-objectid

**Comment by jsejcksn** [comment]
@aliddy23 Ref: https://docs.mongodb.com/manual/reference/method/ObjectId/

```ts
const hex = [...Array(256).keys()]
  .map(index => index.toString(16).padStart(2, '0'));

const createObjectId = (counter?: Uint8Array) => {
  const seconds = Math.floor(Date.now() / 1000);
  const rCounter = counter ?? crypto.getRandomValues(new Uint8Array(3));
  const r = crypto.getRandomValues(new Uint8Array(5));

  return `${seconds.toString(16)}${[...r.values(), ...rCounter.values()].map(int => hex[int]).join('')}`;
};
```

```ts
console.log(createObjectId());
```

**Comment by aliddy23** [comment]
Thank you!

**Comment by jsejcksn** [comment]
@manyuanrong I think more people finding this plugin are going to anticipate the same or similar API to [the Node driver](https://mongodb.github.io/node-mongodb-native/3.6/api/ObjectID.html). I'm not sure if that's an eventual goal of yours or not, but you should probably clarify that in the readme.

**Comment by manyuanrong** [comment]
> @manyuanrong I think more people finding this plugin are going to anticipate the same or similar API to [the Node driver](https://mongodb.github.io/node-mongodb-native/3.6/api/ObjectID.html). I'm not sure if that's an eventual goal of yours or not, but you should probably clarify that in the readme.

I’m still not sure whether to maintain an API similar to the Node.js client, which has some additional costs, not sure how much benefit this will have

**Comment by jsejcksn** [comment]
> I’m still not sure whether to maintain an API similar to the Node.js client, which has some additional costs, not sure how much benefit this will have

That's ok. You are the author and you ultimately decide what goes in. I just think you can avoid some other issues similar to this one by setting more clear expectations about what it does and _doesn't_ do. If you know you won't support certain parts, perhaps you can link to other deno packages in the readme so that people know where to get the functionality.

That being said, I think there are a lot of helpful parts that are provided by the Node driver which aren't provided here yet.

**Comment by manyuanrong** [comment]
@jsejcksn
