### ISSUE TITLE
 CI always fails on Windows

### ISSUE THREAD

**Issue by manyuanrong** [manyuanrong/deno_mongo#81]
CI always fails on Windows, but all tests pass, and I don’t know why it failed. Does anyone know why this is?
![image](https://user-images.githubusercontent.com/7514524/87614616-15c21a80-c743-11ea-941c-b60efe739c54.png)

**Comment by aaronwlee** [comment]
As far as I know, this happens when something connection has not been closed...

**Comment by omaralmgerbie** [comment]
submit an issue here [actions/virtual-environments](https://github.com/actions/virtual-environments/issues) or for something that might help

**Comment by manyuanrong** [comment]
Due to the complete rewrite using TS, this problem should no longer exist now
