### ISSUE TITLE
Adress boundary error

### ISSUE THREAD

**Issue by johny1614** [manyuanrong/deno_mongo#84]
Minimal reproduction steps:

start.ts
```
import { MongoClient } from "https://deno.land/x/mongo@v0.9.1/mod.ts";

const client = new MongoClient();
client.connectWithUri("mongodb://localhost:27017");

const db = client.database("myDataBase");
const users = db.collection("myUsers");

const insertId = await users.insertOne({
	username: "user1",
	password: "pass1",
});

```
Execute with:
`deno run --allow-net --allow-write --allow-read --allow-plugin --unstable start.ts
`
<br>
Result:
No connection to database and error:

> deno run --allow-net --allow-wr…' terminated by signal SIGSEGV (Address boundary error)

Issue is connected to version 0.9.1. Fix for me is downgrading into 0.8.0.

**Comment by lucacasonato** [comment]
Use Deno 1.2.0 with version 0.9.1 of this module.
