### ISSUE TITLE
"thread '<unnamed>' panicked at 'called `Result::unwrap()`" with bad _id

### ISSUE THREAD

**Issue by Guillaume-Lebegue** [manyuanrong/deno_mongo#86]
When calling findById with an _id where a character was removed.
Like `5f23341d003e64540053cbe` instead of `5f23341d003e64540053cbe4`.

It crashes with
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: FromHexError(OddLength)', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\bson-0.14.1\src\bson.rs:575:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It should be a catchable error.

**Comment by WhoAdarshPandya** [comment]
i have similar error like
```thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: FromHexError(InvalidHexCharacter { c: 's', index: 24 })', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\bson-0.14.1\src\bson.rs:575:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by manyuanrong** [comment]
This problem should no longer exist
