### ISSUE TITLE
Generate new ObjectId 

### ISSUE THREAD

**Issue by chantter** [manyuanrong/deno_mongo#92]
Is there chance that you add possibility to generate new Object Id? 
As far I checked right now `ObjectId` it is only a wrapper for `Id` which you have to provide.

https://deno.land/x/mongo@v0.9.2/ts/types.ts

Expected result:
**{ _id: ObjectId() }**

Example in action:
```
collection.updateOne(
        { _id: ObjectId(SOME_ID) },
        {
          $push: {
            modules: {
              _id: ObjectId(),
              name,
            },
          },
        });
```

**Comment by JWebCoder** [comment]
Can we also have the _id.getTimestamp()?

Deno code can be something like:
```typescript
const timestamp = _id.$oid.toString().substring(0,8)
new Date(parseInt(timestamp, 16 ) * 1000)
```
Could be invoked like:
```typescript
ObjectId(_id).getTimestamp()
```

Thank you

**Comment by manyuanrong** [comment]
Currently, an id can be generated by `new Bson.ObjectId()`
```ts
import { Bson } from "https://deno.land/x/mongo@v0.20.0/deps.ts";
const id = new Bson.ObjectId();
```
