### ISSUE TITLE
import mongo@v0.10.0 not found

### ISSUE THREAD

**Issue by bidoubiwa** [manyuanrong/deno_mongo#93]
I tried the getting started and I'm getting this error: 

```bash
Download https://deno.land/x/mongo@v0.10.0/mod.ts
error: Import 'https://deno.land/x/mongo@v0.10.0/mod.ts' failed: 404 Not Found
```
I upgraded deno

```bash
$ deno --version
deno 1.2.3
v8 8.6.334
typescript 3.9.2
```

I tried with the `0.9.0` and it worked, so it has to do with the `0.10.0`.

Any idea what might cause the problem ?

**Comment by manyuanrong** [comment]
#91 It should be the reason for the reconstruction of the deno registry

**Comment by divy-work** [comment]
Consider publishing to other registries as a alternative for users?

**Comment by lucacasonato** [comment]
0.10.1 is published to deno.land/x now
